name: Testing
on: push

jobs:
    test_project:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkpoint@v2
      - name: Run Django unit tests
        run:
          pip install --user django
          python manage.py test